[project]
name = "customizing-pytest-suite-by-hackebrot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs==18.2.0",
    "black==18.9b0",
    "flake8==3.7.6",
    "mypy",
    "pytest>=9.0.3",
]

[tool.uv]
exclude-newer = "30 days"
link-mode = "copy"
